#### DATA CLEANING ######

#KEEP ONLY THE NAME OF THE CITY IN THE CITY COLUMN
UPDATE transactions
SET City = LEFT(City,char_length(City)-7)

#MODIFYING THE DATE COLUMN INTO YYYY-MM-DD FORMAT
UPDATE transactions
SET Date = STR_TO_DATE(Date, '%d-%b-%y')

#DROP INDEX COLUMN
ALTER TABLE transactions
DROP COLUMN `index`

#RENAME COLUMN CARD TYPE
ALTER TABLE transactions 
RENAME COLUMN `Card Type` TO card_type;

#RENAME COLUMN EXP TYPE
ALTER TABLE transactions 
RENAME COLUMN `Exp Type` TO exp_type;

#### DATA ANALYSIS #####

#THE BIGGEST TRANSACTION
SELECT * FROM transactions
ORDER BY Amount DESC
LIMIT 1

#THE TOP 2 MOST COMMON EXPENDITURE TYPES IN TRANSACTIONS
SELECT exp_type, COUNT(*)
FROM transactions
GROUP BY exp_type
ORDER BY COUNT(*) DESC
LIMIT 2

#VIEW ONLY THE TRANSACTIONS FROM CITIES THAT START WITH THE LETTER K
SELECT * FROM transactions
WHERE City RLIKE '^[K].*$'

#AVERAGE TRANSACTION AMOUNTS BY CARD TYPE
SELECT card_type, ROUND(AVG(Amount), 0) AS AVG_AMOUNT
FROM transactions
GROUP BY card_type
ORDER BY AVG_AMOUNT DESC

#AVERAGE TRANSACTION AMOUNTS IN EACH MONTH
SELECT MONTH(Date) AS MONTH, ROUND(AVG(Amount), 0) AS AVG_AMOUNT
FROM transactions
GROUP BY MONTH
ORDER BY MONTH ASC

#COMPARE TRANSACTION VOLUMES AND SUM BY GENDER
SELECT Gender, COUNT(*),
       ROUND((COUNT(*)/(SELECT COUNT(*) FROM transactions))*100, 2) as total_percentage, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM transactions
GROUP BY Gender

#CALCULATE THE TRANSACTION AMOUNT USED FOR FUEL IN DELHI BY MALES
SELECT COUNT(*)
FROM transactions
WHERE Gender = 'M' AND City = 'Delhi' AND exp_type = 'Fuel'

#SEE THE AREAS ON WHICH FEMALES SPEND MONEY ON
SELECT exp_type,
       ROUND((COUNT(*)/(SELECT COUNT(*) FROM transactions))*100, 2) as total_percentage, SUM(Amount) AS AMOUNT_SPENT
FROM transactions
WHERE Gender = 'F'
GROUP BY exp_type
ORDER BY total_percentage DESC

#CALCULATE THE TOTAL AND GROUP TRANSACTION AMOUNTS BY EACH YEAR AND MONTH
SELECT YEAR(Date) AS YEAR, MONTH(Date) AS MONTH, SUM(Amount) AS AMOUNT
FROM transactions
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH ASC

#THE TOP 3 TRANSACTION AMOUNTS BY EACH EXPENDITURE TYPE AND CARD TYPE THE PURCHASE WAS MADE WITH
SELECT *
    FROM (
        SELECT  exp_type,
                ROW_NUMBER() OVER(PARTITION BY exp_type ORDER BY Amount DESC) AS ranking,
                Amount, card_type
            FROM transactions
         ) x
    WHERE ranking <= 3;
    
#THE BIGGEST TRANSACTION AMOUNTS IN EACH CITY AND THE DETAILS ASSOCIATED WITH THEM
SELECT c.*
    FROM ( SELECT City, MAX(Amount) AS Amount
               FROM transactions
               GROUP BY City ) x
    JOIN transactions c USING(City, Amount)
    ORDER BY City ASC